### ISSUE TITLE
Option to add metadata to the thumbnail.

### ISSUE THREAD

**Issue by albertoloscerritos** [Meikul/obsidian-thumbnails#10]
Hi, me again. I have another idea, that I hope can improve the plugin.
The option to add metadata to the code block will help a lot when searching for videos e.g. sometimes I remember the name of a video (or the name of the channel), but not the name of the note where I placed the thumbnail. Currently we can't search for neither the name of the channel or of the video of thumbnails.
Solution: And an option to add the name of the video and of the channel to the code block as metadata. That way the thumbnail stays the same (visually), but we now have the option to search for the thumbnail information.

The following picture shows how we can search for text inside the code block of the thumbnail, but currently we can only search for the link itself, which isn't that helpful.
![thumb_search_1](https://github.com/Meikul/obsidian-thumbnails/assets/16707033/1e9af906-03e8-41ec-83a5-0eb5c125f57f)

Hope you like the idea.

**Comment by Meikul** [comment]
That's a great point, I hadn't thought about searchability.

Funnily enough, there's a feature that does this already. If you turn on `Save Thumbnail Info` in the settings, it adds all that info into the code block. I was just thinking about avoiding the API call, though, not how that would also make it more searchable. Maybe I'll make it enabled by default because of that.

**Comment by albertoloscerritos** [comment]
I just gave it a try, and this is just what I was looking for.
Glad you liked the idea :)
