### ISSUE TITLE
Option to view the date a video was uploaded.

### ISSUE THREAD

**Issue by albertoloscerritos** [Meikul/obsidian-thumbnails#12]
Hi, me again. I think the option to view the date a video was uploaded is key piece of information for most video. Especially when working with many video thumbnails. 

I thinks the following area:
![image](https://github.com/Meikul/obsidian-thumbnails/assets/16707033/5cf20161-b7d2-411a-90a9-8e275958f3ca)
Would perfectly fit the uploaded date without making the thumbnail look cluttered. 
Thanks for your time.

**Comment by Meikul** [comment]
This would be nice along with potentially having the view count there too. Unfortunately, I can't get that information through the way the plugin normally gets video info. Like in issue #9 I could get that information from the Youtube API, but only if the user has an API token set and I don't think many users do. So, since very few users would be able to use this feature, it's not worth making the plugin more complicated. Thanks for the idea though!
